import os

f = open('../../source/Constants.hx', 'w')

def textify(path):
    arr = [line.strip() for line in open(path, 'r').readlines()]
    return '        constantsMap["{}"] = \n            {};\n\n'.format(path, str(arr))

opening_str = '''package;

class Constants {
    // AUTOGENERATED BY `assets/data/constants_gen.py` -- do not edit!
    
    public static var constantsMap:Map<String, Array<String>>;

    public static function loadMap() {
        constantsMap = new Map<String, Array<String>>();
'''

closing_str = '''    }\n}'''

f.write(opening_str)

for suffix in ['background', 'foreground', 'foreground2', 'params']:
    for world in ['world', 'shrine1', 'shrine2', 'shrine3', 'shrine4',
                  'shrine5', 'shrine6', 'shrine7', 'shrine8']:
        file_tag = '{}_{}.csv'.format(world, suffix)
        if os.path.exists(file_tag):
            f.write(textify(file_tag))

for one_off in ['solid_tiles']:
    file_tag = '{}.csv'.format(one_off)
    if os.path.exists(file_tag):
        f.write(textify(file_tag))
    else:
        print('No one-off found for {}; continuing...', one_off)

f.write(closing_str)

f.close()
